### PR TITLE
Laravel 10 support

### PR DESCRIPTION
**Pull request by amirsadeghi1**

### CODE REVIEW

**Comment by zoispag** [comment]
@pascalbaljet can this be merged?

**Comment by pascalbaljet** [comment]
Waits for https://github.com/GrahamCampbell/Laravel-Security/pull/47

**Comment by hakimzulkufli** [comment]
> Waits for [GrahamCampbell/Laravel-Security#47](https://github.com/GrahamCampbell/Laravel-Security/pull/47)

Hi @pascalbaljet and @amirsadeghi1, just wanna let you know Laravel-Security v11.0 for Laravel 10 support has been released.

**Comment by pascalbaljet** [comment]
Fixed in v1.4

**Pull request merged**
